//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using Newtonsoft.Json;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("TchillrDataBaseModel", "FK_Keywords_0", "Activities", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TchillrREST.DataModel.Activity), "Keywords", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TchillrREST.DataModel.Keyword), true)]
[assembly: EdmRelationshipAttribute("TchillrDataBaseModel", "FK_Occurences_0", "Activities", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TchillrREST.DataModel.Activity), "Occurences", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TchillrREST.DataModel.Occurence), true)]
[assembly: EdmRelationshipAttribute("TchillrDataBaseModel", "FK_Rubriques_0", "Activities", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TchillrREST.DataModel.Activity), "Rubriques", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TchillrREST.DataModel.Rubrique), true)]
[assembly: EdmRelationshipAttribute("TchillrDataBaseModel", "FK_WordClouds_0", "Tags", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TchillrREST.DataModel.Tag), "WordClouds", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TchillrREST.DataModel.WordCloud), true)]
[assembly: EdmRelationshipAttribute("TchillrDataBaseModel", "FK_Media_0", "Activity", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TchillrREST.DataModel.Activity), "Medium", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TchillrREST.DataModel.Medium), true)]
[assembly: EdmRelationshipAttribute("TchillrDataBaseModel", "FK_Tags_01", "Theme", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(TchillrREST.DataModel.Theme), "Tag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TchillrREST.DataModel.Tag), true)]

#endregion

namespace TchillrREST.DataModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Activity> Activities
        {
            get
            {
                if ((_Activities == null))
                {
                    _Activities = base.CreateObjectSet<Activity>("Activities");
                }
                return _Activities;
            }
        }
        private ObjectSet<Activity> _Activities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Category> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Category>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Category> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Keyword> Keywords
        {
            get
            {
                if ((_Keywords == null))
                {
                    _Keywords = base.CreateObjectSet<Keyword>("Keywords");
                }
                return _Keywords;
            }
        }
        private ObjectSet<Keyword> _Keywords;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Occurence> Occurences
        {
            get
            {
                if ((_Occurences == null))
                {
                    _Occurences = base.CreateObjectSet<Occurence>("Occurences");
                }
                return _Occurences;
            }
        }
        private ObjectSet<Occurence> _Occurences;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Rubrique> Rubriques
        {
            get
            {
                if ((_Rubriques == null))
                {
                    _Rubriques = base.CreateObjectSet<Rubrique>("Rubriques");
                }
                return _Rubriques;
            }
        }
        private ObjectSet<Rubrique> _Rubriques;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tag> Tags
        {
            get
            {
                if ((_Tags == null))
                {
                    _Tags = base.CreateObjectSet<Tag>("Tags");
                }
                return _Tags;
            }
        }
        private ObjectSet<Tag> _Tags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Theme> Themes
        {
            get
            {
                if ((_Themes == null))
                {
                    _Themes = base.CreateObjectSet<Theme>("Themes");
                }
                return _Themes;
            }
        }
        private ObjectSet<Theme> _Themes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserTag> UserTags
        {
            get
            {
                if ((_UserTags == null))
                {
                    _UserTags = base.CreateObjectSet<UserTag>("UserTags");
                }
                return _UserTags;
            }
        }
        private ObjectSet<UserTag> _UserTags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<WordCloud> WordClouds
        {
            get
            {
                if ((_WordClouds == null))
                {
                    _WordClouds = base.CreateObjectSet<WordCloud>("WordClouds");
                }
                return _WordClouds;
            }
        }
        private ObjectSet<WordCloud> _WordClouds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Medium> Media
        {
            get
            {
                if ((_Media == null))
                {
                    _Media = base.CreateObjectSet<Medium>("Media");
                }
                return _Media;
            }
        }
        private ObjectSet<Medium> _Media;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserActivity> UserActivities
        {
            get
            {
                if ((_UserActivities == null))
                {
                    _UserActivities = base.CreateObjectSet<UserActivity>("UserActivities");
                }
                return _UserActivities;
            }
        }
        private ObjectSet<UserActivity> _UserActivities;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Activities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToActivities(Activity activity)
        {
            base.AddObject("Activities", activity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Category category)
        {
            base.AddObject("Categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Keywords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKeywords(Keyword keyword)
        {
            base.AddObject("Keywords", keyword);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Occurences EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOccurences(Occurence occurence)
        {
            base.AddObject("Occurences", occurence);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rubriques EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRubriques(Rubrique rubrique)
        {
            base.AddObject("Rubriques", rubrique);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTags(Tag tag)
        {
            base.AddObject("Tags", tag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Themes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToThemes(Theme theme)
        {
            base.AddObject("Themes", theme);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserTags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserTags(UserTag userTag)
        {
            base.AddObject("UserTags", userTag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the WordClouds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWordClouds(WordCloud wordCloud)
        {
            base.AddObject("WordClouds", wordCloud);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Media EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMedia(Medium medium)
        {
            base.AddObject("Media", medium);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserActivities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserActivities(UserActivity userActivity)
        {
            base.AddObject("UserActivities", userActivity);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TchillrDataBaseModel", Name="Activity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Activity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Activity object.
        /// </summary>
        /// <param name="identifier">Initial value of the identifier property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static Activity CreateActivity(global::System.Int32 identifier, global::System.String name)
        {
            Activity activity = new Activity();
            activity.identifier = identifier;
            activity.name = name;
            return activity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 identifier
        {
            get
            {
                return _identifier;
            }
            set
            {
                if (_identifier != value)
                {
                    OnidentifierChanging(value);
                    ReportPropertyChanging("identifier");
                    _identifier = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("identifier");
                    OnidentifierChanged();
                }
            }
        }
        private global::System.Int32 _identifier;
        partial void OnidentifierChanging(global::System.Int32 value);
        partial void OnidentifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String shortDescription
        {
            get
            {
                return _shortDescription;
            }
            set
            {
                OnshortDescriptionChanging(value);
                ReportPropertyChanging("shortDescription");
                _shortDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("shortDescription");
                OnshortDescriptionChanged();
            }
        }
        private global::System.String _shortDescription;
        partial void OnshortDescriptionChanging(global::System.String value);
        partial void OnshortDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String place
        {
            get
            {
                return _place;
            }
            set
            {
                OnplaceChanging(value);
                ReportPropertyChanging("place");
                _place = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("place");
                OnplaceChanged();
            }
        }
        private global::System.String _place;
        partial void OnplaceChanging(global::System.String value);
        partial void OnplaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String adress
        {
            get
            {
                return _adress;
            }
            set
            {
                OnadressChanging(value);
                ReportPropertyChanging("adress");
                _adress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("adress");
                OnadressChanged();
            }
        }
        private global::System.String _adress;
        partial void OnadressChanging(global::System.String value);
        partial void OnadressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> longitude
        {
            get
            {
                return _longitude;
            }
            set
            {
                OnlongitudeChanging(value);
                ReportPropertyChanging("longitude");
                _longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("longitude");
                OnlongitudeChanged();
            }
        }
        private Nullable<global::System.Double> _longitude;
        partial void OnlongitudeChanging(Nullable<global::System.Double> value);
        partial void OnlongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> latitude
        {
            get
            {
                return _latitude;
            }
            set
            {
                OnlatitudeChanging(value);
                ReportPropertyChanging("latitude");
                _latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("latitude");
                OnlatitudeChanged();
            }
        }
        private Nullable<global::System.Double> _latitude;
        partial void OnlatitudeChanging(Nullable<global::System.Double> value);
        partial void OnlatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> zipcode
        {
            get
            {
                return _zipcode;
            }
            set
            {
                OnzipcodeChanging(value);
                ReportPropertyChanging("zipcode");
                _zipcode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("zipcode");
                OnzipcodeChanged();
            }
        }
        private Nullable<global::System.Int32> _zipcode;
        partial void OnzipcodeChanging(Nullable<global::System.Int32> value);
        partial void OnzipcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String accessType
        {
            get
            {
                return _accessType;
            }
            set
            {
                OnaccessTypeChanging(value);
                ReportPropertyChanging("accessType");
                _accessType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("accessType");
                OnaccessTypeChanged();
            }
        }
        private global::System.String _accessType;
        partial void OnaccessTypeChanging(global::System.String value);
        partial void OnaccessTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idorganisateurs
        {
            get
            {
                return _idorganisateurs;
            }
            set
            {
                OnidorganisateursChanging(value);
                ReportPropertyChanging("idorganisateurs");
                _idorganisateurs = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idorganisateurs");
                OnidorganisateursChanged();
            }
        }
        private Nullable<global::System.Int32> _idorganisateurs;
        partial void OnidorganisateursChanging(Nullable<global::System.Int32> value);
        partial void OnidorganisateursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idlieux
        {
            get
            {
                return _idlieux;
            }
            set
            {
                OnidlieuxChanging(value);
                ReportPropertyChanging("idlieux");
                _idlieux = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idlieux");
                OnidlieuxChanged();
            }
        }
        private Nullable<global::System.Int32> _idlieux;
        partial void OnidlieuxChanging(Nullable<global::System.Int32> value);
        partial void OnidlieuxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> updated
        {
            get
            {
                return _updated;
            }
            set
            {
                OnupdatedChanging(value);
                ReportPropertyChanging("updated");
                _updated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("updated");
                OnupdatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _updated;
        partial void OnupdatedChanging(Nullable<global::System.DateTime> value);
        partial void OnupdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String price
        {
            get
            {
                return _price;
            }
            set
            {
                OnpriceChanging(value);
                ReportPropertyChanging("price");
                _price = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("price");
                OnpriceChanged();
            }
        }
        private global::System.String _price;
        partial void OnpriceChanging(global::System.String value);
        partial void OnpriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String metro
        {
            get
            {
                return _metro;
            }
            set
            {
                OnmetroChanging(value);
                ReportPropertyChanging("metro");
                _metro = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("metro");
                OnmetroChanged();
            }
        }
        private global::System.String _metro;
        partial void OnmetroChanging(global::System.String value);
        partial void OnmetroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String velib
        {
            get
            {
                return _velib;
            }
            set
            {
                OnvelibChanging(value);
                ReportPropertyChanging("velib");
                _velib = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("velib");
                OnvelibChanged();
            }
        }
        private global::System.String _velib;
        partial void OnvelibChanging(global::System.String value);
        partial void OnvelibChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bus
        {
            get
            {
                return _bus;
            }
            set
            {
                OnbusChanging(value);
                ReportPropertyChanging("bus");
                _bus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bus");
                OnbusChanged();
            }
        }
        private global::System.String _bus;
        partial void OnbusChanging(global::System.String value);
        partial void OnbusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> created
        {
            get
            {
                return _created;
            }
            set
            {
                OncreatedChanging(value);
                ReportPropertyChanging("created");
                _created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("created");
                OncreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _created;
        partial void OncreatedChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String organisateur
        {
            get
            {
                return _organisateur;
            }
            set
            {
                OnorganisateurChanging(value);
                ReportPropertyChanging("organisateur");
                _organisateur = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("organisateur");
                OnorganisateurChanged();
            }
        }
        private global::System.String _organisateur;
        partial void OnorganisateurChanging(global::System.String value);
        partial void OnorganisateurChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String hasFee
        {
            get
            {
                return _hasFee;
            }
            set
            {
                OnhasFeeChanging(value);
                ReportPropertyChanging("hasFee");
                _hasFee = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("hasFee");
                OnhasFeeChanged();
            }
        }
        private global::System.String _hasFee;
        partial void OnhasFeeChanging(global::System.String value);
        partial void OnhasFeeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TchillrDataBaseModel", "FK_Keywords_0", "Keywords")]
        public EntityCollection<Keyword> Keywords
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Keyword>("TchillrDataBaseModel.FK_Keywords_0", "Keywords");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Keyword>("TchillrDataBaseModel.FK_Keywords_0", "Keywords", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TchillrDataBaseModel", "FK_Occurences_0", "Occurences")]
        [JsonIgnore]
        public EntityCollection<Occurence> Occurences
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Occurence>("TchillrDataBaseModel.FK_Occurences_0", "Occurences");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Occurence>("TchillrDataBaseModel.FK_Occurences_0", "Occurences", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TchillrDataBaseModel", "FK_Rubriques_0", "Rubriques")]
        public EntityCollection<Rubrique> Rubriques
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Rubrique>("TchillrDataBaseModel.FK_Rubriques_0", "Rubriques");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Rubrique>("TchillrDataBaseModel.FK_Rubriques_0", "Rubriques", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TchillrDataBaseModel", "FK_Media_0", "Medium")]
        public EntityCollection<Medium> Media
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Medium>("TchillrDataBaseModel.FK_Media_0", "Medium");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Medium>("TchillrDataBaseModel.FK_Media_0", "Medium", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TchillrDataBaseModel", Name="Category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Category object.
        /// </summary>
        /// <param name="idCategorie">Initial value of the IdCategorie property.</param>
        /// <param name="nom">Initial value of the Nom property.</param>
        public static Category CreateCategory(global::System.Int32 idCategorie, global::System.String nom)
        {
            Category category = new Category();
            category.IdCategorie = idCategorie;
            category.Nom = nom;
            return category;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCategorie
        {
            get
            {
                return _IdCategorie;
            }
            set
            {
                if (_IdCategorie != value)
                {
                    OnIdCategorieChanging(value);
                    ReportPropertyChanging("IdCategorie");
                    _IdCategorie = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCategorie");
                    OnIdCategorieChanged();
                }
            }
        }
        private global::System.Int32 _IdCategorie;
        partial void OnIdCategorieChanging(global::System.Int32 value);
        partial void OnIdCategorieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nom
        {
            get
            {
                return _Nom;
            }
            set
            {
                OnNomChanging(value);
                ReportPropertyChanging("Nom");
                _Nom = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nom");
                OnNomChanged();
            }
        }
        private global::System.String _Nom;
        partial void OnNomChanging(global::System.String value);
        partial void OnNomChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TchillrDataBaseModel", Name="Keyword")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Keyword : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Keyword object.
        /// </summary>
        /// <param name="activityID">Initial value of the activityID property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="hits">Initial value of the hits property.</param>
        public static Keyword CreateKeyword(global::System.Int32 activityID, global::System.String title, global::System.Int32 hits)
        {
            Keyword keyword = new Keyword();
            keyword.activityID = activityID;
            keyword.title = title;
            keyword.hits = hits;
            return keyword;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 activityID
        {
            get
            {
                return _activityID;
            }
            set
            {
                if (_activityID != value)
                {
                    OnactivityIDChanging(value);
                    ReportPropertyChanging("activityID");
                    _activityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("activityID");
                    OnactivityIDChanged();
                }
            }
        }
        private global::System.Int32 _activityID;
        partial void OnactivityIDChanging(global::System.Int32 value);
        partial void OnactivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                if (_title != value)
                {
                    OntitleChanging(value);
                    ReportPropertyChanging("title");
                    _title = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("title");
                    OntitleChanged();
                }
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 hits
        {
            get
            {
                return _hits;
            }
            set
            {
                if (_hits != value)
                {
                    OnhitsChanging(value);
                    ReportPropertyChanging("hits");
                    _hits = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("hits");
                    OnhitsChanged();
                }
            }
        }
        private global::System.Int32 _hits;
        partial void OnhitsChanging(global::System.Int32 value);
        partial void OnhitsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TchillrDataBaseModel", "FK_Keywords_0", "Activities")]
        public Activity Activity
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Activity>("TchillrDataBaseModel.FK_Keywords_0", "Activities").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Activity>("TchillrDataBaseModel.FK_Keywords_0", "Activities").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Activity> ActivityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Activity>("TchillrDataBaseModel.FK_Keywords_0", "Activities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Activity>("TchillrDataBaseModel.FK_Keywords_0", "Activities", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TchillrDataBaseModel", Name="Medium")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Medium : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Medium object.
        /// </summary>
        /// <param name="activityID">Initial value of the activityID property.</param>
        /// <param name="path">Initial value of the path property.</param>
        /// <param name="type">Initial value of the type property.</param>
        /// <param name="credit">Initial value of the credit property.</param>
        /// <param name="caption">Initial value of the caption property.</param>
        public static Medium CreateMedium(global::System.Int32 activityID, global::System.String path, global::System.String type, global::System.String credit, global::System.String caption)
        {
            Medium medium = new Medium();
            medium.activityID = activityID;
            medium.path = path;
            medium.type = type;
            medium.credit = credit;
            medium.caption = caption;
            return medium;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 activityID
        {
            get
            {
                return _activityID;
            }
            set
            {
                if (_activityID != value)
                {
                    OnactivityIDChanging(value);
                    ReportPropertyChanging("activityID");
                    _activityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("activityID");
                    OnactivityIDChanged();
                }
            }
        }
        private global::System.Int32 _activityID;
        partial void OnactivityIDChanging(global::System.Int32 value);
        partial void OnactivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String path
        {
            get
            {
                return _path;
            }
            set
            {
                if (_path != value)
                {
                    OnpathChanging(value);
                    ReportPropertyChanging("path");
                    _path = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("path");
                    OnpathChanged();
                }
            }
        }
        private global::System.String _path;
        partial void OnpathChanging(global::System.String value);
        partial void OnpathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                if (_type != value)
                {
                    OntypeChanging(value);
                    ReportPropertyChanging("type");
                    _type = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("type");
                    OntypeChanged();
                }
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String credit
        {
            get
            {
                return _credit;
            }
            set
            {
                if (_credit != value)
                {
                    OncreditChanging(value);
                    ReportPropertyChanging("credit");
                    _credit = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("credit");
                    OncreditChanged();
                }
            }
        }
        private global::System.String _credit;
        partial void OncreditChanging(global::System.String value);
        partial void OncreditChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String caption
        {
            get
            {
                return _caption;
            }
            set
            {
                if (_caption != value)
                {
                    OncaptionChanging(value);
                    ReportPropertyChanging("caption");
                    _caption = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("caption");
                    OncaptionChanged();
                }
            }
        }
        private global::System.String _caption;
        partial void OncaptionChanging(global::System.String value);
        partial void OncaptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TchillrDataBaseModel", "FK_Media_0", "Activity")]
        public Activity Activity
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Activity>("TchillrDataBaseModel.FK_Media_0", "Activity").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Activity>("TchillrDataBaseModel.FK_Media_0", "Activity").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Activity> ActivityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Activity>("TchillrDataBaseModel.FK_Media_0", "Activity");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Activity>("TchillrDataBaseModel.FK_Media_0", "Activity", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TchillrDataBaseModel", Name="Occurence")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Occurence : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Occurence object.
        /// </summary>
        /// <param name="activityID">Initial value of the ActivityID property.</param>
        /// <param name="jour">Initial value of the jour property.</param>
        /// <param name="hour_start">Initial value of the hour_start property.</param>
        /// <param name="hour_end">Initial value of the hour_end property.</param>
        public static Occurence CreateOccurence(global::System.Int32 activityID, global::System.DateTime jour, global::System.TimeSpan hour_start, global::System.TimeSpan hour_end)
        {
            Occurence occurence = new Occurence();
            occurence.ActivityID = activityID;
            occurence.jour = jour;
            occurence.hour_start = hour_start;
            occurence.hour_end = hour_end;
            return occurence;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ActivityID
        {
            get
            {
                return _ActivityID;
            }
            set
            {
                if (_ActivityID != value)
                {
                    OnActivityIDChanging(value);
                    ReportPropertyChanging("ActivityID");
                    _ActivityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ActivityID");
                    OnActivityIDChanged();
                }
            }
        }
        private global::System.Int32 _ActivityID;
        partial void OnActivityIDChanging(global::System.Int32 value);
        partial void OnActivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime jour
        {
            get
            {
                return _jour;
            }
            set
            {
                if (_jour != value)
                {
                    OnjourChanging(value);
                    ReportPropertyChanging("jour");
                    _jour = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("jour");
                    OnjourChanged();
                }
            }
        }
        private global::System.DateTime _jour;
        partial void OnjourChanging(global::System.DateTime value);
        partial void OnjourChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan hour_start
        {
            get
            {
                return _hour_start;
            }
            set
            {
                if (_hour_start != value)
                {
                    Onhour_startChanging(value);
                    ReportPropertyChanging("hour_start");
                    _hour_start = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("hour_start");
                    Onhour_startChanged();
                }
            }
        }
        private global::System.TimeSpan _hour_start;
        partial void Onhour_startChanging(global::System.TimeSpan value);
        partial void Onhour_startChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan hour_end
        {
            get
            {
                return _hour_end;
            }
            set
            {
                if (_hour_end != value)
                {
                    Onhour_endChanging(value);
                    ReportPropertyChanging("hour_end");
                    _hour_end = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("hour_end");
                    Onhour_endChanged();
                }
            }
        }
        private global::System.TimeSpan _hour_end;
        partial void Onhour_endChanging(global::System.TimeSpan value);
        partial void Onhour_endChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TchillrDataBaseModel", "FK_Occurences_0", "Activities")]
        public Activity Activity
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Activity>("TchillrDataBaseModel.FK_Occurences_0", "Activities").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Activity>("TchillrDataBaseModel.FK_Occurences_0", "Activities").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Activity> ActivityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Activity>("TchillrDataBaseModel.FK_Occurences_0", "Activities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Activity>("TchillrDataBaseModel.FK_Occurences_0", "Activities", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TchillrDataBaseModel", Name="Rubrique")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Rubrique : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Rubrique object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="activityID">Initial value of the activityID property.</param>
        /// <param name="identifier">Initial value of the identifier property.</param>
        public static Rubrique CreateRubrique(global::System.String name, global::System.Int32 activityID, global::System.Int32 identifier)
        {
            Rubrique rubrique = new Rubrique();
            rubrique.name = name;
            rubrique.activityID = activityID;
            rubrique.identifier = identifier;
            return rubrique;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 activityID
        {
            get
            {
                return _activityID;
            }
            set
            {
                OnactivityIDChanging(value);
                ReportPropertyChanging("activityID");
                _activityID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("activityID");
                OnactivityIDChanged();
            }
        }
        private global::System.Int32 _activityID;
        partial void OnactivityIDChanging(global::System.Int32 value);
        partial void OnactivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 identifier
        {
            get
            {
                return _identifier;
            }
            set
            {
                if (_identifier != value)
                {
                    OnidentifierChanging(value);
                    ReportPropertyChanging("identifier");
                    _identifier = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("identifier");
                    OnidentifierChanged();
                }
            }
        }
        private global::System.Int32 _identifier;
        partial void OnidentifierChanging(global::System.Int32 value);
        partial void OnidentifierChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TchillrDataBaseModel", "FK_Rubriques_0", "Activities")]
        public Activity Activity
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Activity>("TchillrDataBaseModel.FK_Rubriques_0", "Activities").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Activity>("TchillrDataBaseModel.FK_Rubriques_0", "Activities").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Activity> ActivityReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Activity>("TchillrDataBaseModel.FK_Rubriques_0", "Activities");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Activity>("TchillrDataBaseModel.FK_Rubriques_0", "Activities", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TchillrDataBaseModel", Name="Tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="identifier">Initial value of the identifier property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="weight">Initial value of the weight property.</param>
        public static Tag CreateTag(global::System.Int32 identifier, global::System.String title, global::System.Int32 weight)
        {
            Tag tag = new Tag();
            tag.identifier = identifier;
            tag.title = title;
            tag.weight = weight;
            return tag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 identifier
        {
            get
            {
                return _identifier;
            }
            set
            {
                if (_identifier != value)
                {
                    OnidentifierChanging(value);
                    ReportPropertyChanging("identifier");
                    _identifier = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("identifier");
                    OnidentifierChanged();
                }
            }
        }
        private global::System.Int32 _identifier;
        partial void OnidentifierChanging(global::System.Int32 value);
        partial void OnidentifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 weight
        {
            get
            {
                return _weight;
            }
            set
            {
                OnweightChanging(value);
                ReportPropertyChanging("weight");
                _weight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("weight");
                OnweightChanged();
            }
        }
        private global::System.Int32 _weight;
        partial void OnweightChanging(global::System.Int32 value);
        partial void OnweightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> themeID
        {
            get
            {
                return _themeID;
            }
            set
            {
                OnthemeIDChanging(value);
                ReportPropertyChanging("themeID");
                _themeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("themeID");
                OnthemeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _themeID;
        partial void OnthemeIDChanging(Nullable<global::System.Int32> value);
        partial void OnthemeIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TchillrDataBaseModel", "FK_WordClouds_0", "WordClouds")]
        public EntityCollection<WordCloud> WordClouds
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WordCloud>("TchillrDataBaseModel.FK_WordClouds_0", "WordClouds");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WordCloud>("TchillrDataBaseModel.FK_WordClouds_0", "WordClouds", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TchillrDataBaseModel", "FK_Tags_01", "Theme")]
        public Theme Theme
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("TchillrDataBaseModel.FK_Tags_01", "Theme").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("TchillrDataBaseModel.FK_Tags_01", "Theme").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Theme> ThemeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theme>("TchillrDataBaseModel.FK_Tags_01", "Theme");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Theme>("TchillrDataBaseModel.FK_Tags_01", "Theme", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TchillrDataBaseModel", Name="Theme")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Theme : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Theme object.
        /// </summary>
        /// <param name="identifier">Initial value of the identifier property.</param>
        /// <param name="title">Initial value of the title property.</param>
        public static Theme CreateTheme(global::System.Int32 identifier, global::System.String title)
        {
            Theme theme = new Theme();
            theme.identifier = identifier;
            theme.title = title;
            return theme;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 identifier
        {
            get
            {
                return _identifier;
            }
            set
            {
                if (_identifier != value)
                {
                    OnidentifierChanging(value);
                    ReportPropertyChanging("identifier");
                    _identifier = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("identifier");
                    OnidentifierChanged();
                }
            }
        }
        private global::System.Int32 _identifier;
        partial void OnidentifierChanging(global::System.Int32 value);
        partial void OnidentifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TchillrDataBaseModel", "FK_Tags_01", "Tag")]
        public EntityCollection<Tag> Tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tag>("TchillrDataBaseModel.FK_Tags_01", "Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tag>("TchillrDataBaseModel.FK_Tags_01", "Tag", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TchillrDataBaseModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="identifier">Initial value of the identifier property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static User CreateUser(global::System.Guid identifier, global::System.String name)
        {
            User user = new User();
            user.identifier = identifier;
            user.name = name;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid identifier
        {
            get
            {
                return _identifier;
            }
            set
            {
                if (_identifier != value)
                {
                    OnidentifierChanging(value);
                    ReportPropertyChanging("identifier");
                    _identifier = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("identifier");
                    OnidentifierChanged();
                }
            }
        }
        private global::System.Guid _identifier;
        partial void OnidentifierChanging(global::System.Guid value);
        partial void OnidentifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TchillrDataBaseModel", Name="UserActivity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserActivity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserActivity object.
        /// </summary>
        /// <param name="identifier">Initial value of the identifier property.</param>
        /// <param name="activityID">Initial value of the activityID property.</param>
        /// <param name="keywords">Initial value of the keywords property.</param>
        /// <param name="userID">Initial value of the userID property.</param>
        /// <param name="occurence_jour">Initial value of the occurence_jour property.</param>
        /// <param name="occurence_hour_start">Initial value of the occurence_hour_start property.</param>
        /// <param name="occurence_hour_end">Initial value of the occurence_hour_end property.</param>
        public static UserActivity CreateUserActivity(global::System.Int32 identifier, global::System.Int32 activityID, global::System.String keywords, global::System.Int32 userID, global::System.DateTime occurence_jour, global::System.TimeSpan occurence_hour_start, global::System.TimeSpan occurence_hour_end)
        {
            UserActivity userActivity = new UserActivity();
            userActivity.identifier = identifier;
            userActivity.activityID = activityID;
            userActivity.keywords = keywords;
            userActivity.userID = userID;
            userActivity.occurence_jour = occurence_jour;
            userActivity.occurence_hour_start = occurence_hour_start;
            userActivity.occurence_hour_end = occurence_hour_end;
            return userActivity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 identifier
        {
            get
            {
                return _identifier;
            }
            set
            {
                if (_identifier != value)
                {
                    OnidentifierChanging(value);
                    ReportPropertyChanging("identifier");
                    _identifier = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("identifier");
                    OnidentifierChanged();
                }
            }
        }
        private global::System.Int32 _identifier;
        partial void OnidentifierChanging(global::System.Int32 value);
        partial void OnidentifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 activityID
        {
            get
            {
                return _activityID;
            }
            set
            {
                if (_activityID != value)
                {
                    OnactivityIDChanging(value);
                    ReportPropertyChanging("activityID");
                    _activityID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("activityID");
                    OnactivityIDChanged();
                }
            }
        }
        private global::System.Int32 _activityID;
        partial void OnactivityIDChanging(global::System.Int32 value);
        partial void OnactivityIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String keywords
        {
            get
            {
                return _keywords;
            }
            set
            {
                OnkeywordsChanging(value);
                ReportPropertyChanging("keywords");
                _keywords = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("keywords");
                OnkeywordsChanged();
            }
        }
        private global::System.String _keywords;
        partial void OnkeywordsChanging(global::System.String value);
        partial void OnkeywordsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String transport_mode
        {
            get
            {
                return _transport_mode;
            }
            set
            {
                Ontransport_modeChanging(value);
                ReportPropertyChanging("transport_mode");
                _transport_mode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("transport_mode");
                Ontransport_modeChanged();
            }
        }
        private global::System.String _transport_mode;
        partial void Ontransport_modeChanging(global::System.String value);
        partial void Ontransport_modeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 userID
        {
            get
            {
                return _userID;
            }
            set
            {
                if (_userID != value)
                {
                    OnuserIDChanging(value);
                    ReportPropertyChanging("userID");
                    _userID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("userID");
                    OnuserIDChanged();
                }
            }
        }
        private global::System.Int32 _userID;
        partial void OnuserIDChanging(global::System.Int32 value);
        partial void OnuserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime occurence_jour
        {
            get
            {
                return _occurence_jour;
            }
            set
            {
                Onoccurence_jourChanging(value);
                ReportPropertyChanging("occurence_jour");
                _occurence_jour = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("occurence_jour");
                Onoccurence_jourChanged();
            }
        }
        private global::System.DateTime _occurence_jour;
        partial void Onoccurence_jourChanging(global::System.DateTime value);
        partial void Onoccurence_jourChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan occurence_hour_start
        {
            get
            {
                return _occurence_hour_start;
            }
            set
            {
                Onoccurence_hour_startChanging(value);
                ReportPropertyChanging("occurence_hour_start");
                _occurence_hour_start = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("occurence_hour_start");
                Onoccurence_hour_startChanged();
            }
        }
        private global::System.TimeSpan _occurence_hour_start;
        partial void Onoccurence_hour_startChanging(global::System.TimeSpan value);
        partial void Onoccurence_hour_startChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.TimeSpan occurence_hour_end
        {
            get
            {
                return _occurence_hour_end;
            }
            set
            {
                Onoccurence_hour_endChanging(value);
                ReportPropertyChanging("occurence_hour_end");
                _occurence_hour_end = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("occurence_hour_end");
                Onoccurence_hour_endChanged();
            }
        }
        private global::System.TimeSpan _occurence_hour_end;
        partial void Onoccurence_hour_endChanging(global::System.TimeSpan value);
        partial void Onoccurence_hour_endChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private Nullable<global::System.Int32> _status;
        partial void OnstatusChanging(Nullable<global::System.Int32> value);
        partial void OnstatusChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TchillrDataBaseModel", Name="UserTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserTag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserTag object.
        /// </summary>
        /// <param name="identifier">Initial value of the identifier property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="tagID">Initial value of the TagID property.</param>
        public static UserTag CreateUserTag(global::System.Int32 identifier, global::System.Guid userID, global::System.Int32 tagID)
        {
            UserTag userTag = new UserTag();
            userTag.identifier = identifier;
            userTag.UserID = userID;
            userTag.TagID = tagID;
            return userTag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 identifier
        {
            get
            {
                return _identifier;
            }
            set
            {
                if (_identifier != value)
                {
                    OnidentifierChanging(value);
                    ReportPropertyChanging("identifier");
                    _identifier = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("identifier");
                    OnidentifierChanged();
                }
            }
        }
        private global::System.Int32 _identifier;
        partial void OnidentifierChanging(global::System.Int32 value);
        partial void OnidentifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Guid _UserID;
        partial void OnUserIDChanging(global::System.Guid value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TagID
        {
            get
            {
                return _TagID;
            }
            set
            {
                OnTagIDChanging(value);
                ReportPropertyChanging("TagID");
                _TagID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TagID");
                OnTagIDChanged();
            }
        }
        private global::System.Int32 _TagID;
        partial void OnTagIDChanging(global::System.Int32 value);
        partial void OnTagIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TchillrDataBaseModel", Name="WordCloud")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WordCloud : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new WordCloud object.
        /// </summary>
        /// <param name="identifier">Initial value of the identifier property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="tagID">Initial value of the tagID property.</param>
        public static WordCloud CreateWordCloud(global::System.Int32 identifier, global::System.String title, global::System.Int32 tagID)
        {
            WordCloud wordCloud = new WordCloud();
            wordCloud.identifier = identifier;
            wordCloud.title = title;
            wordCloud.tagID = tagID;
            return wordCloud;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 identifier
        {
            get
            {
                return _identifier;
            }
            set
            {
                if (_identifier != value)
                {
                    OnidentifierChanging(value);
                    ReportPropertyChanging("identifier");
                    _identifier = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("identifier");
                    OnidentifierChanged();
                }
            }
        }
        private global::System.Int32 _identifier;
        partial void OnidentifierChanging(global::System.Int32 value);
        partial void OnidentifierChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tagID
        {
            get
            {
                return _tagID;
            }
            set
            {
                OntagIDChanging(value);
                ReportPropertyChanging("tagID");
                _tagID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tagID");
                OntagIDChanged();
            }
        }
        private global::System.Int32 _tagID;
        partial void OntagIDChanging(global::System.Int32 value);
        partial void OntagIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("TchillrDataBaseModel", "FK_WordClouds_0", "Tags")]
        public Tag Tag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tag>("TchillrDataBaseModel.FK_WordClouds_0", "Tags").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tag>("TchillrDataBaseModel.FK_WordClouds_0", "Tags").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tag> TagReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tag>("TchillrDataBaseModel.FK_WordClouds_0", "Tags");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tag>("TchillrDataBaseModel.FK_WordClouds_0", "Tags", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
